### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by vincentchalamon**
- [x] Rebase from your fork
- [x] Fix unit tests
- [x] Fix Behat tests
- [x] Apply cs-fixer

### CODE REVIEW

**Comment by vincentchalamon** [comment]
Behat tests don't have to test full JSON response, only `hydra:members` & `@context` can be tested, but no necessity for `hydra:search` each time.
`the JSON should be valid according to this schema:` check can be used instead, especially if you update your config to prevent to update `hydra:search` node in all `.feature` files

**Comment by teohhanhui** [comment]
@vincentchalamon +1 I think most of the Behat tests in this bundle suffer from that.

**Comment by vincentchalamon** [comment]
@teohhanhui Good

**Comment by teohhanhui** [comment]
Merged and squashed.

**Pull request closed without merging**
