### PR TITLE
Fix filters review

### PR DESCRIPTION
**Pull request by vincentchalamon**
- [x] Fix comments from https://github.com/dunglas/DunglasApiBundle/pull/242
- [x] Rebase from `origin/master`

**This PR cannot be automatically merged cause your branch `filter_nested` is not up to date with `origin/master`. Please rebase it**

### CODE REVIEW

**Comment by teohhanhui** [comment]
@vincentchalamon It looks like you've accidentally rebased onto my `master` branch instead of `filter_nested` branch (which is now up to date with `master` branch of [dunglas/DunglasApiBundle](https://github.com/dunglas/DunglasApiBundle)). Please correct that.

**Comment by vincentchalamon** [comment]
@teohhanhui I can't see your comments anymore since I rebased… I'll create a new PR, can you review it ?
By memory, I was reading about renaming `QueryFactory` to split it on 2 classes: `…Validator` & `QueryNameGenerator` (something like that). I disagree about `…Validator` cause it's not a Symfony validator and name can be confused. What do you think of `QueryHelper` ?

**Comment by teohhanhui** [comment]
Yes, `Validator` is probably not a good idea. `QueryHelper` suffers from the same issues as `QueryUtils`, I think. It's not specific about its purpose.

**Comment by teohhanhui** [comment]
The question becomes "helping with what?"

**Comment by teohhanhui** [comment]
Some alternatives: `PaginationQueryChecker`, `PaginationQueryTester` (the "test" part is probably problematic though).

**Comment by vincentchalamon** [comment]
It's not only about pagination, but I agree with `checker` (I prefer it instead of `tester`).
What about `QueryChecker` (maybe you already purpose it in previous hidden comments) ?

**Comment by teohhanhui** [comment]
`QueryChecker`, `QueryNameGenerator` and `RequestParser` it is then? :smiley:

I also suggested `RequestParser::parseKeepSpecialCharacters` or `RequestParser::duplicateRequestRestoreSpecialCharacters`.

**Comment by vincentchalamon** [comment]
OK for me for these naming & splits. Can you do it in [this PR](https://github.com/teohhanhui/DunglasApiBundle/pull/4) ? Or I can do it but not before this weekend

**Pull request closed without merging**
